# Generated by Django 5.0.8 on 2024-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='hrname',
            new_name='ad_grps',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='sname',
            new_name='dashboard',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='input',
            new_name='pri_grp',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='send',
            new_name='remote',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='output',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='type',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='uname',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
