# Generated by Django 5.0.8 on 2024-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
