# Generated by Django 5.0.8 on 2024-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tenant',
            field=models.IntegerField(default='0'),
        ),
    ]
