# Generated by Django 5.0.8 on 2024-10-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenusmodel',
            name='menu_priority',
        ),
    ]
