# Generated by Django 5.0.8 on 2024-10-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('owner', models.TextField(max_length=100)),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VariableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('initiator_type', models.CharField(max_length=10)),
                ('initiator_id', models.BigIntegerField()),
                ('value', models.TextField(max_length=350)),
            ],
        ),
    ]
