# Generated by Django 5.0.8 on 2024-10-20 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_formmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
