services:
  frontend:
    container_name: frontend
    build:
      context: ./runtime/
      dockerfile: Dockerfile
    volumes:
      - ./runtime/:/code/runtime/
      - ./runtime/src:/code/runtime/src/
      - ./runtime/public:/code/runtime/public/
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
    ports:
      - 8000:8000

  postgres:
    container_name: postgres
    image: postgres:16.3-bullseye
    ports:
      - 5432:5432
    volumes:
      - /var/lib/pgsql/data:/var/lib/postgresql/data

  proxy:
    image: traefik:v3.1
    container_name: proxy
    ports:
      - 8011:8011
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
