defaultEntryPoints = ["http"]

[log]
level = "DEBUG"

[api]
dashboard = true

[accessLog]


[providers]
providersThrottleDuration = 10
[providers.file]
filename = "traefik.toml"
directory = "/etc/traefik/"
watch = true


[entryPoints]
[entryPoints.web]
address = ":8011"
    [entryPoints.web.forwardedHeaders]
      insecure = true
  [entryPoints.tcp]
    address = ":5432"
    [entryPoints.tcp.transport]
      [entryPoints.tcp.transport.respondingTimeouts]
        idleTimeout = "120s"  # Time the TCP connection can stay idle before closing
        readTimeout = "60s"   # Time Traefik waits for Postgres to start responding

[http.routers]

[http.routers.django]
service = "django"
rule = "PathPrefix(`/accounts`) || PathPrefix(`/_allauth`) || PathPrefix(`/api`)"
entrypoints = ["web"]


[http.routers.react]
service = "react"
rule = "PathPrefix(`/`)"
entrypoints = ["web"]

[http.services]
[http.services.react.loadBalancer]
[[http.services.react.loadBalancer.servers]]
url = "http://frontend:3000"
[http.services.django.loadBalancer]
[[http.services.django.loadBalancer.servers]]
url = "http://backend:8000"