# Generated by Django 5.0.8 on 2024-10-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptmodel',
            old_name='sname',
            new_name='s_name',
        ),
        migrations.AddField(
            model_name='scriptmodel',
            name='f_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptmodel',
            name='path',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
