# Generated by Django 5.0.8 on 2024-10-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_rename_sname_scriptmodel_s_name_scriptmodel_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptmodel',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='scriptmodel',
            old_name='email',
            new_name='s_emails',
        ),
        migrations.RenameField(
            model_name='scriptmodel',
            old_name='send',
            new_name='s_send_data',
        ),
    ]
