# Generated by Django 5.0.8 on 2024-10-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantmodel',
            old_name='desc',
            new_name='description',
        ),
    ]
