# Generated by Django 5.0.8 on 2024-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=25)),
                ('type', models.TextField(max_length=100)),
                ('pri_ip', models.CharField(max_length=20)),
                ('sec_ip', models.CharField(max_length=20)),
                ('term_ip', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=75)),
                ('hw_vendor', models.CharField(max_length=75)),
                ('hw_type', models.TextField(max_length=100)),
                ('datacenter', models.EmailField(max_length=150)),
                ('dc_row', models.CharField(max_length=30)),
                ('dc_rack', models.CharField(max_length=30)),
                ('dc_u_num', models.CharField(max_length=30)),
                ('virtual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CloudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('terraform', models.BooleanField()),
                ('api_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=25)),
                ('vlan_id', models.TextField(max_length=100)),
                ('public', models.CharField(max_length=20)),
                ('firwalled', models.CharField(max_length=20)),
                ('proxy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=20)),
                ('term_ip', models.CharField(max_length=20)),
                ('o_s', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=75)),
                ('hw_vendor', models.CharField(max_length=75)),
                ('hw_type', models.TextField(max_length=100)),
                ('cpu_count', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('datacenter', models.EmailField(max_length=150)),
                ('dc_row', models.CharField(max_length=30)),
                ('dc_rack', models.CharField(max_length=30)),
                ('dc_u_num', models.CharField(max_length=30)),
                ('virtual', models.BooleanField()),
            ],
        ),
    ]
