# Generated by Django 5.0.8 on 2024-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermodel',
            name='description',
            field=models.TextField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
