# Generated by Django 5.0.8 on 2024-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_servermodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermodel',
            name='datacenter',
            field=models.CharField(max_length=150),
        ),
    ]
