# Generated by Django 5.0.8 on 2024-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_description_taskmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='yaml_file',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
