# Generated by Django 5.0.8 on 2024-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskmodel_yaml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='input',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='output',
            field=models.CharField(max_length=500),
        ),
    ]
