# Generated by Django 5.0.8 on 2024-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_email_alter_taskmodel_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='input',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='output',
            field=models.TextField(max_length=500),
        ),
    ]
