# Generated by Django 5.0.8 on 2024-10-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='send',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='sname',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='group',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='input',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
