# Generated by Django 5.0.8 on 2024-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_groupmodel_email_remove_groupmodel_send_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='input',
            new_name='ad_map',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='hrname',
            new_name='ap_permissions',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='ldap_map',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
